"""phase2 universe and model store

Revision ID: 61a0d6afb99d
Revises: 26af05232c30
Create Date: 2026-10-07 04:27:35.654969+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61a0d6afb99d'
down_revision: Union[str, None] = '26af05232c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_class', sa.String(length=64), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('esg_flag', sa.Boolean(), nullable=False),
    sa.Column('shariah_flag', sa.Boolean(), nullable=False),
    sa.Column('ethical_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('liquidity_tier', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('model_metrics_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_source', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_versions_is_current'), 'model_metrics_versions', ['is_current'], unique=False)
    op.create_table('covariance_artifacts',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=True),
    sa.Column('ticker_order', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('matrix_inline', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('shrinkage', sa.String(length=32), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['model_metrics_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('instrument_metrics',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=64), nullable=True),
    sa.Column('expected_annual_return_pct', sa.Float(), nullable=True),
    sa.Column('volatility_pct', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('risk_profile', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['model_metrics_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'ticker')
    )
    op.create_table('lstm_views',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('view_return_pct', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['model_metrics_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', 'ticker')
    )
    op.create_table('price_series',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['instruments.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_series')
    op.drop_table('lstm_views')
    op.drop_table('instrument_metrics')
    op.drop_table('covariance_artifacts')
    op.drop_index(op.f('ix_model_metrics_versions_is_current'), table_name='model_metrics_versions')
    op.drop_table('model_metrics_versions')
    op.drop_table('instruments')
    # ### end Alembic commands ###
