"""initial schema

Revision ID: 26af05232c30
Revises: 
Create Date: 2026-10-06 14:49:33.420112+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26af05232c30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_metrics_cache',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_version', sa.String(length=16), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=True),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('allocation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('backtest_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('projection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('metrics_version_id', sa.Uuid(), nullable=True),
    sa.Column('lstm_view_applied', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=True),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('financial_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('income_currency', sa.String(length=3), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('existing_savings', sa.Float(), nullable=True),
    sa.Column('monthly_debt_emi', sa.Float(), nullable=True),
    sa.Column('emergency_fund_months', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=16), nullable=True),
    sa.Column('liquidity_need_horizon_months', sa.Integer(), nullable=True),
    sa.Column('country_of_residence', sa.String(length=2), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_sectors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_class_prefs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('esg_only', sa.Boolean(), nullable=False),
    sa.Column('shariah_only', sa.Boolean(), nullable=False),
    sa.Column('ethical_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('excluded_sectors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('excluded_tickers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('existing_holdings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('allow_crypto', sa.Boolean(), nullable=False),
    sa.Column('allow_international', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('saved_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('recommendation_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_snapshot_id'], ['recommendation_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_plans_user_id'), ['user_id'], unique=False)

    op.create_table('user_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credentials')
    with op.batch_alter_table('saved_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_plans_user_id'))

    op.drop_table('saved_plans')
    op.drop_table('preferences')
    op.drop_table('financial_profiles')
    op.drop_table('users')
    op.drop_table('recommendation_snapshots')
    op.drop_table('model_metrics_cache')
    # ### end Alembic commands ###
